# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terra3 < Formula
  desc "A CLI to manage AWS deployments based on the Terr3 stack!"
  homepage "https://terra3.io/"
  version "0.0.5"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.5/terra3_Darwin_amd64.tar.gz"
      sha256 "cd0bf7d3024f0b422b4d4c169c993f09ca8f3c35be9ded5807371ac9b7b6ac3e"

      def install
        bin.install "terra3"
      end
    end
    on_arm do
      url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.5/terra3_Darwin_arm64.tar.gz"
      sha256 "6d03547c807daa7d1d604f96a4d6fc03c2674f50f2d6e46ee3e74d73453f0089"

      def install
        bin.install "terra3"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.5/terra3_Linux_amd64.tar.gz"
        sha256 "80aeb8d62ad07bc1552adaaa3d857a33fc280e35efcb908e4abc6fbe86ad4313"

        def install
          bin.install "terra3"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/it-objects/terra3-cli/releases/download/v0.0.5/terra3_Linux_arm64.tar.gz"
        sha256 "bb8314c05db693721902056f3bc8080712fb713ff8f406bb4a22eabcd5270733"

        def install
          bin.install "terra3"
        end
      end
    end
  end
end
